site_name: linktiles docs

nav:
  - Home: index.md
  - Installation: installation.md
  - Configuration: configuration.md
  - User Guide: user_guide.md

theme:
  name: material
  palette:
    scheme: slate
    primary: black
  features:
    - content.code.copy
  logo: assets/logo.svg
  favicon: assets/logo.svg

plugins:
  - search

markdown_extensions: 
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.blocks.tab:
      alternate_style: true
  - admonition
